
name: Universal DevSecOps Pipeline

on:
  push:
    branches:
      - main

jobs:

  security-scan:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .

      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1

  build-and-push:

    runs-on: ubuntu-latest

    needs: security-scan

    steps:

      - name: Checkout
        uses: actions/checkout@v4









        - name: Docker Login
        run: |
          echo "${ secrets.DOCKER_TOKEN }" | docker login -u "${ secrets.DOCKER_USERNAME }" --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/root:${{ github.sha }} .

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/root:${{ github.sha }}

  deploy:

    runs-on: ubuntu-latest

    needs: build-and-push

    steps:

      - name: Deploy Placeholder
        run: echo "Continuous Deployment Running..."
